version 2:

sources:
  - name: airbnb
    database: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
      - name: reviews
        identifier: raw_reviews
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
      - name: hosts
        identifier: raw_hosts
        loaded_at_field: date
    
